### PR TITLE
Make BracketsJS ready for production

### PR DESCRIPTION
**Pull request by dinonull**
After this, we should be able to successfully release v1.4.

### CODE REVIEW

**Comment by dinonull** [comment]
Also, the aliases will not work since the webpack only allows you to export one table

**Comment by dinonull** [comment]
It would be best if instead of using brackets to access the library we could use $ or _.

**Comment by JaydenDev** [comment]
Please verify that your PR is complete, if not mark it as a draft. Do not reopen closed PRs unless not merged, merged closed PRs are not to be repoped.

**Comment by dinonull** [comment]
I have tested this on my own fork and it works, so this PR is complete

**Pull request merged**
